# .github/workflows/prod-pipeline.yml
# This is a github action pipeline for production.
name: Production Deployment
on: 
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
# Jobs
jobs:
  build-prod:
      runs-on: ubuntu-latest
      env:
        CI: true
        build_env: production
      steps:
      # Checkout the code
        - uses: actions/checkout@v2
      # Run Tests
        - name: Run Unit Tests
          uses: actions/setup-node@v1
          with: 
            node-version: 12.x
        - run: |
            yarn
            yarn test --watchAll=false
      # Build Code
        - name: Build Static Site
          uses: actions/setup-node@v1
          with: 
            node-version: 12.x  
        - run: |
            yarn
            yarn build
            ls -al
          env:
            REACT_APP_CONFIG: ${{ env.build_env }}
      # Upload build to github artifact
        - name: Upload build artifact to Github
          uses: actions/upload-artifact@v1
          with:
            name: build-artifact
            path: build/
  deploy-prod:
name: Deploy To Production
    runs-on: ubuntu-latest
    env:
      bucket: "<% index .Params `productionFrontendSubdomain` %><% index .Params `productionHostRoot` %>"
      region: "<% index .Params `region` %>"
    steps:
      # Clone repo
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
      # Clone repo with custom ref
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
       # Configure Aws account for S3 Sync
      - name: Configure AWS credentials for S3 sync
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}
      # Deploy to s3
      - name: Sync with S3
        run: |
          cd stage-build-artifact
          aws s3 sync . s3://${{ env.bucket }}
      # Invalidate Cloudfront
      - name: Invalidate Cloudfront
        run: |
          export DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[?@=='${{ env.bucket }}']].Id | [0]" | tr -d '"')
          aws cloudfront create-invalidation --distribution-id ${DIST_ID} --paths "/*"
 